//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.SampleSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWeatherRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetWeatherRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        private WindowsFormsClient.SampleSvc.TemperatureType TemperatureTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WindowsFormsClient.SampleSvc.TemperatureType TemperatureType {
            get {
                return this.TemperatureTypeField;
            }
            set {
                if ((this.TemperatureTypeField.Equals(value) != true)) {
                    this.TemperatureTypeField = value;
                    this.RaisePropertyChanged("TemperatureType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureType", Namespace="http://tempuri.org/")]
    public enum TemperatureType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fahrenheit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Celsius = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetWeatherResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WindowsFormsClient.SampleSvc.TemperatureCondition ConditionField;
        
        private int TemperatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WindowsFormsClient.SampleSvc.TemperatureCondition Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((this.ConditionField.Equals(value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureCondition", Namespace="http://tempuri.org/")]
    public enum TemperatureCondition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rainy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunny = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cloudy = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThunderStorm = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleSvc.SampleServiceSoap")]
    public interface SampleServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsClient.SampleSvc.HelloWorldResponse HelloWorld(WindowsFormsClient.SampleSvc.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(WindowsFormsClient.SampleSvc.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsClient.SampleSvc.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReverseString", ReplyAction="*")]
        WindowsFormsClient.SampleSvc.ReverseStringResponse ReverseString(WindowsFormsClient.SampleSvc.ReverseStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ReverseString", ReplyAction="*")]
        System.IAsyncResult BeginReverseString(WindowsFormsClient.SampleSvc.ReverseStringRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsClient.SampleSvc.ReverseStringResponse EndReverseString(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name req from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeature", ReplyAction="*")]
        WindowsFormsClient.SampleSvc.GetWeatureResponse GetWeature(WindowsFormsClient.SampleSvc.GetWeatureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWeature", ReplyAction="*")]
        System.IAsyncResult BeginGetWeature(WindowsFormsClient.SampleSvc.GetWeatureRequest request, System.AsyncCallback callback, object asyncState);
        
        WindowsFormsClient.SampleSvc.GetWeatureResponse EndGetWeature(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsClient.SampleSvc.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsClient.SampleSvc.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseString", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.ReverseStringRequestBody Body;
        
        public ReverseStringRequest() {
        }
        
        public ReverseStringRequest(WindowsFormsClient.SampleSvc.ReverseStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReverseStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public ReverseStringRequestBody() {
        }
        
        public ReverseStringRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.ReverseStringResponseBody Body;
        
        public ReverseStringResponse() {
        }
        
        public ReverseStringResponse(WindowsFormsClient.SampleSvc.ReverseStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReverseStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReverseStringResult;
        
        public ReverseStringResponseBody() {
        }
        
        public ReverseStringResponseBody(string ReverseStringResult) {
            this.ReverseStringResult = ReverseStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeature", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.GetWeatureRequestBody Body;
        
        public GetWeatureRequest() {
        }
        
        public GetWeatureRequest(WindowsFormsClient.SampleSvc.GetWeatureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.SampleSvc.GetWeatherRequest req;
        
        public GetWeatureRequestBody() {
        }
        
        public GetWeatureRequestBody(WindowsFormsClient.SampleSvc.GetWeatherRequest req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatureResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsClient.SampleSvc.GetWeatureResponseBody Body;
        
        public GetWeatureResponse() {
        }
        
        public GetWeatureResponse(WindowsFormsClient.SampleSvc.GetWeatureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsClient.SampleSvc.GetWeatherResponse GetWeatureResult;
        
        public GetWeatureResponseBody() {
        }
        
        public GetWeatureResponseBody(WindowsFormsClient.SampleSvc.GetWeatherResponse GetWeatureResult) {
            this.GetWeatureResult = GetWeatureResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleServiceSoapChannel : WindowsFormsClient.SampleSvc.SampleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReverseStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReverseStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWeatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWeatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WindowsFormsClient.SampleSvc.GetWeatherResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WindowsFormsClient.SampleSvc.GetWeatherResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsClient.SampleSvc.SampleServiceSoap>, WindowsFormsClient.SampleSvc.SampleServiceSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginReverseStringDelegate;
        
        private EndOperationDelegate onEndReverseStringDelegate;
        
        private System.Threading.SendOrPostCallback onReverseStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWeatureDelegate;
        
        private EndOperationDelegate onEndGetWeatureDelegate;
        
        private System.Threading.SendOrPostCallback onGetWeatureCompletedDelegate;
        
        public SampleServiceSoapClient() {
        }
        
        public SampleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<ReverseStringCompletedEventArgs> ReverseStringCompleted;
        
        public event System.EventHandler<GetWeatureCompletedEventArgs> GetWeatureCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.HelloWorldResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.HelloWorld(WindowsFormsClient.SampleSvc.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsClient.SampleSvc.HelloWorldRequest inValue = new WindowsFormsClient.SampleSvc.HelloWorldRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.HelloWorldRequestBody();
            WindowsFormsClient.SampleSvc.HelloWorldResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsClient.SampleSvc.SampleServiceSoap.BeginHelloWorld(WindowsFormsClient.SampleSvc.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            WindowsFormsClient.SampleSvc.HelloWorldRequest inValue = new WindowsFormsClient.SampleSvc.HelloWorldRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.HelloWorldRequestBody();
            return ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.HelloWorldResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHelloWorld(System.IAsyncResult result) {
            WindowsFormsClient.SampleSvc.HelloWorldResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.ReverseStringResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.ReverseString(WindowsFormsClient.SampleSvc.ReverseStringRequest request) {
            return base.Channel.ReverseString(request);
        }
        
        public string ReverseString(string str) {
            WindowsFormsClient.SampleSvc.ReverseStringRequest inValue = new WindowsFormsClient.SampleSvc.ReverseStringRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.ReverseStringRequestBody();
            inValue.Body.str = str;
            WindowsFormsClient.SampleSvc.ReverseStringResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).ReverseString(inValue);
            return retVal.Body.ReverseStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsClient.SampleSvc.SampleServiceSoap.BeginReverseString(WindowsFormsClient.SampleSvc.ReverseStringRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReverseString(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReverseString(string str, System.AsyncCallback callback, object asyncState) {
            WindowsFormsClient.SampleSvc.ReverseStringRequest inValue = new WindowsFormsClient.SampleSvc.ReverseStringRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.ReverseStringRequestBody();
            inValue.Body.str = str;
            return ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).BeginReverseString(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.ReverseStringResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.EndReverseString(System.IAsyncResult result) {
            return base.Channel.EndReverseString(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndReverseString(System.IAsyncResult result) {
            WindowsFormsClient.SampleSvc.ReverseStringResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).EndReverseString(result);
            return retVal.Body.ReverseStringResult;
        }
        
        private System.IAsyncResult OnBeginReverseString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string str = ((string)(inValues[0]));
            return this.BeginReverseString(str, callback, asyncState);
        }
        
        private object[] OnEndReverseString(System.IAsyncResult result) {
            string retVal = this.EndReverseString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReverseStringCompleted(object state) {
            if ((this.ReverseStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReverseStringCompleted(this, new ReverseStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReverseStringAsync(string str) {
            this.ReverseStringAsync(str, null);
        }
        
        public void ReverseStringAsync(string str, object userState) {
            if ((this.onBeginReverseStringDelegate == null)) {
                this.onBeginReverseStringDelegate = new BeginOperationDelegate(this.OnBeginReverseString);
            }
            if ((this.onEndReverseStringDelegate == null)) {
                this.onEndReverseStringDelegate = new EndOperationDelegate(this.OnEndReverseString);
            }
            if ((this.onReverseStringCompletedDelegate == null)) {
                this.onReverseStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReverseStringCompleted);
            }
            base.InvokeAsync(this.onBeginReverseStringDelegate, new object[] {
                        str}, this.onEndReverseStringDelegate, this.onReverseStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.GetWeatureResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.GetWeature(WindowsFormsClient.SampleSvc.GetWeatureRequest request) {
            return base.Channel.GetWeature(request);
        }
        
        public WindowsFormsClient.SampleSvc.GetWeatherResponse GetWeature(WindowsFormsClient.SampleSvc.GetWeatherRequest req) {
            WindowsFormsClient.SampleSvc.GetWeatureRequest inValue = new WindowsFormsClient.SampleSvc.GetWeatureRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.GetWeatureRequestBody();
            inValue.Body.req = req;
            WindowsFormsClient.SampleSvc.GetWeatureResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).GetWeature(inValue);
            return retVal.Body.GetWeatureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsFormsClient.SampleSvc.SampleServiceSoap.BeginGetWeature(WindowsFormsClient.SampleSvc.GetWeatureRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWeature(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetWeature(WindowsFormsClient.SampleSvc.GetWeatherRequest req, System.AsyncCallback callback, object asyncState) {
            WindowsFormsClient.SampleSvc.GetWeatureRequest inValue = new WindowsFormsClient.SampleSvc.GetWeatureRequest();
            inValue.Body = new WindowsFormsClient.SampleSvc.GetWeatureRequestBody();
            inValue.Body.req = req;
            return ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).BeginGetWeature(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsClient.SampleSvc.GetWeatureResponse WindowsFormsClient.SampleSvc.SampleServiceSoap.EndGetWeature(System.IAsyncResult result) {
            return base.Channel.EndGetWeature(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WindowsFormsClient.SampleSvc.GetWeatherResponse EndGetWeature(System.IAsyncResult result) {
            WindowsFormsClient.SampleSvc.GetWeatureResponse retVal = ((WindowsFormsClient.SampleSvc.SampleServiceSoap)(this)).EndGetWeature(result);
            return retVal.Body.GetWeatureResult;
        }
        
        private System.IAsyncResult OnBeginGetWeature(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WindowsFormsClient.SampleSvc.GetWeatherRequest req = ((WindowsFormsClient.SampleSvc.GetWeatherRequest)(inValues[0]));
            return this.BeginGetWeature(req, callback, asyncState);
        }
        
        private object[] OnEndGetWeature(System.IAsyncResult result) {
            WindowsFormsClient.SampleSvc.GetWeatherResponse retVal = this.EndGetWeature(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWeatureCompleted(object state) {
            if ((this.GetWeatureCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWeatureCompleted(this, new GetWeatureCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWeatureAsync(WindowsFormsClient.SampleSvc.GetWeatherRequest req) {
            this.GetWeatureAsync(req, null);
        }
        
        public void GetWeatureAsync(WindowsFormsClient.SampleSvc.GetWeatherRequest req, object userState) {
            if ((this.onBeginGetWeatureDelegate == null)) {
                this.onBeginGetWeatureDelegate = new BeginOperationDelegate(this.OnBeginGetWeature);
            }
            if ((this.onEndGetWeatureDelegate == null)) {
                this.onEndGetWeatureDelegate = new EndOperationDelegate(this.OnEndGetWeature);
            }
            if ((this.onGetWeatureCompletedDelegate == null)) {
                this.onGetWeatureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWeatureCompleted);
            }
            base.InvokeAsync(this.onBeginGetWeatureDelegate, new object[] {
                        req}, this.onEndGetWeatureDelegate, this.onGetWeatureCompletedDelegate, userState);
        }
    }
}
